mod util;

#[test]
fn pretty_print_error() {
    const SOURCE: &'static str = r#"declare register X["#;

    const EXPECTED_ERROR: &'static str = r#" --> 1:19
  |
1 |    declare register X[
  |                      ^
  |
  = found: "[", expected one of:
           "," ...
           "(" ...
           <NUM_BIN> ...
           <NUM_HEX> ...
           <NUM_DEC> ...
           <NUM_BIT_STRING> ...
           "declare" ...
           "nop" ...
           "goto" ...
           "read" ...
           "write" ...
           "if" ...
           "switch" ...
           "assert" ...
           <ID> ..."#;

    let error = util::parse_err(SOURCE);
    let error_message = rt_easy_parser::pretty_print_error(&error, SOURCE, None, false);

    assert_eq!(error_message, EXPECTED_ERROR);
}
