name: test-vhdl

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache crate
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            test-vhdl/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('test-vhdl/Cargo.lock') }}

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Setup ghdl
        uses: ghdl/setup-ghdl-ci@nightly
        with:
          backend: mcode

      - name: Run tests
        run: cargo run
        working-directory: test-vhdl
